version: 0.2
env:
  parameter-store:
    AWS_REGION: /cicd-techtalk/aws/region

phases:
  install:
    runtime-versions:
      nodejs: 10

  build:
    commands:
      - echo Build started on `date`
      - echo "{\"region\":\"$AWS_REGION\"}" > app/config/config.json

artifacts:
  secondary-artifacts:
    project:
      files:
        - 'app/**/*'
        - 'scripts/**'
    appspec:
      files:
        - deploy/appspec.yml
      discard-paths: yes